#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# shellcheck source=scripts/session_env.sh
source "$(dirname "$0")/session_env.sh"

print_help() {
  cat <<'EOF'
Usage:
  scripts/dev_session.sh help
  scripts/dev_session.sh checklist
  scripts/dev_session.sh configure
  scripts/dev_session.sh doctor
  scripts/dev_session.sh review

Commands:
  help       Show this help.
  checklist  Print the recommended local development session checklist.
  configure  Interactively create a private runtime session.env file.
  doctor     Check local tools and required environment variables.
  review     Run the local command bundle review server with its embedded watcher.
EOF
}

print_checklist() {
  cat <<'EOF'
Workspace Terminal Bridge development session checklist

1. Check local prerequisites:
   scripts/dev_session.sh doctor

2. If MCP_ACCESS_TOKEN or NGROK_HOST is missing, create a private runtime env file:
   scripts/dev_session.sh configure

3. Start the local approval UI:
   scripts/dev_session.sh review

4. Start the MCP server in another terminal:
   scripts/run_server.sh

5. Start ngrok in another terminal:
   scripts/run_ngrok.sh

6. Keep the review dashboard open:
   http://127.0.0.1:8790/pending

7. Configure the ChatGPT app MCP URL with this format:
   https://<NGROK_HOST>/mcp?access_token=<TOKEN>

Notes:
  - Token values are intentionally not printed by this helper.
  - If server.py or MCP tool schemas change, restart the MCP server and Refresh the ChatGPT app.
  - If only the review UI, watcher, or README changes, MCP server restart and ChatGPT app Refresh are usually not needed.
EOF
}

doctor() {
  local exit_code=0

  load_session_env

  echo "Workspace Terminal Bridge doctor"
  echo

  if [[ -f "$SESSION_ENV" ]]; then
    local session_mode
    session_mode="$(stat -f "%Lp" "$SESSION_ENV" 2>/dev/null || stat -c "%a" "$SESSION_ENV" 2>/dev/null || echo unknown)"
    echo "[ok] session.env: found at $SESSION_ENV"
    if [[ "$session_mode" != "600" ]]; then
      echo "[warn] session.env permissions are $session_mode; recommended: chmod 600 $SESSION_ENV"
    fi
  else
    echo "[info] session.env: not found; run scripts/dev_session.sh configure if you want runtime env auto-loading."
  fi

  if command -v uv >/dev/null 2>&1; then
    echo "[ok] uv: found"
  else
    echo "[error] uv: missing"
    exit_code=1
  fi

  if command -v ngrok >/dev/null 2>&1; then
    echo "[ok] ngrok: found"
  else
    echo "[warn] ngrok: missing; scripts/run_ngrok.sh will fail until ngrok is installed."
  fi

  if command -v terminal-notifier >/dev/null 2>&1; then
    echo "[ok] terminal-notifier: found"
  else
    echo "[warn] terminal-notifier: missing; clickable macOS notifications require it."
    echo "       Install with: brew install terminal-notifier"
  fi

  if [[ -n "${MCP_ACCESS_TOKEN:-}" ]]; then
    echo "[ok] MCP_ACCESS_TOKEN: set"
  else
    echo "[warn] MCP_ACCESS_TOKEN: not set; scripts/run_server.sh may fail."
  fi

  if [[ -n "${NGROK_HOST:-}" || -n "${NGROK_BASE_URL:-}" ]]; then
    echo "[ok] NGROK_HOST/NGROK_BASE_URL: set"
  else
    echo "[warn] NGROK_HOST/NGROK_BASE_URL: not set; scripts/run_ngrok.sh will use its default host."
  fi

  return "$exit_code"
}

configure() {
  load_session_env

  mkdir -p "$RUNTIME_ROOT"
  chmod 700 "$RUNTIME_ROOT" 2>/dev/null || true

  local token="${MCP_ACCESS_TOKEN:-}"
  local token_input=""
  local ngrok_host="${NGROK_HOST:-${NGROK_BASE_URL:-}}"
  local ngrok_input=""
  local mcp_host="${MCP_HOST:-127.0.0.1}"
  local mcp_port="${MCP_PORT:-8787}"

  echo "Workspace Terminal Bridge session env configure"
  echo "Target: $SESSION_ENV"
  echo

  if [[ -n "$token" ]]; then
    read -r -s -p "MCP_ACCESS_TOKEN is already set. Press Enter to keep it, or type a new value: " token_input
    echo
    if [[ -n "$token_input" ]]; then
      token="$token_input"
    fi
  else
    read -r -s -p "MCP_ACCESS_TOKEN: " token
    echo
    if [[ -z "$token" ]]; then
      echo "[error] MCP_ACCESS_TOKEN is required."
      return 1
    fi
  fi

  ngrok_host="$(normalize_ngrok_host "$ngrok_host")"
  if [[ -n "$ngrok_host" ]]; then
    read -r -p "NGROK_HOST [$ngrok_host]: " ngrok_input
    if [[ -n "$ngrok_input" ]]; then
      ngrok_host="$(normalize_ngrok_host "$ngrok_input")"
    fi
  else
    read -r -p "NGROK_HOST, for example your-domain.ngrok-free.app: " ngrok_host
    ngrok_host="$(normalize_ngrok_host "$ngrok_host")"
    if [[ -z "$ngrok_host" ]]; then
      echo "[error] NGROK_HOST is required."
      return 1
    fi
  fi

  umask 077
  {
    echo "# Generated by scripts/dev_session.sh configure"
    echo "# Stored outside the git repository. Do not commit token values."
    echo "export MCP_ACCESS_TOKEN=$(shell_quote "$token")"
    echo "export NGROK_HOST=$(shell_quote "$ngrok_host")"
    echo "export MCP_HOST=$(shell_quote "$mcp_host")"
    echo "export MCP_PORT=$(shell_quote "$mcp_port")"
  } > "$SESSION_ENV"
  chmod 600 "$SESSION_ENV"

  echo
  echo "Saved private session environment: $SESSION_ENV"
  echo "MCP_ACCESS_TOKEN: set"
  echo "NGROK_HOST: $ngrok_host"
  echo
  echo "The helper scripts auto-load this file. To use it in your current shell too, run:"
  echo "  source $SESSION_ENV"
}

review() {
  load_session_env

  if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:8790 -sTCP:LISTEN >/dev/null 2>&1; then
    echo "[error] Port 8790 is already in use."
    echo "Stop the existing review server first:"
    echo "  lsof -tiTCP:8790 -sTCP:LISTEN | xargs kill"
    echo "Then run:"
    echo "  scripts/dev_session.sh review"
    return 1
  fi

  echo "Starting command bundle review server with embedded watcher..."
  echo "Embedded watcher: ${BUNDLE_REVIEW_EMBEDDED_WATCHER:-1}"
  echo "Review dashboard: http://127.0.0.1:8790/pending"
  echo "Disable embedded watcher: BUNDLE_REVIEW_EMBEDDED_WATCHER=0 scripts/dev_session.sh review"
  echo "Standalone watcher fallback: uv run python scripts/command_bundle_watcher.py"
  echo "Press Ctrl-C to stop the review server."
  echo

  exec uv run python scripts/command_bundle_review_server.py
}

cmd="${1:-help}"

case "$cmd" in
  help)
    print_help
    ;;
  checklist)
    print_checklist
    ;;
  configure)
    configure
    ;;
  doctor)
    doctor
    ;;
  review)
    review
    ;;
  *)
    print_help >&2
    exit 2
    ;;
esac
